id: I09583FC4
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3872-final
source_file: null
initial_creation_type: input
imported: '2022-07-27T11:24:23.124315'
last_modified: '2022-07-27T11:24:23.124332'
parser: null
source_metadata:
  title: ཐུན་མོང་གི་རྩ་བ།
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
